# Generated by Django 5.2.4 on 2025-07-14 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_needs', models.TextField()),
                ('program_details', models.CharField(max_length=255)),
                ('preferred_format', models.CharField(max_length=50)),
                ('required_hours', models.PositiveIntegerField()),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
